<!DOCTYPE html>
<html>
<head>
  <title>Список пользователей</title>
</head>
<body>
  <h1>Список пользователей</h1>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Nname</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($users as $user): ?>
        <tr>
          <td><?= $user['id'] ?></td>
          <td><?= htmlspecialchars($user['nickname']) ?></td>
          <td><?= htmlspecialchars($user['email']) ?></td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
</body>
</html>